### PR TITLE
yaegi: update symbols for go1.14/gonum0.7.0

### PR DESCRIPTION
**Pull request by kortschak**
Please take a look.

### CODE REVIEW

**Comment by vladimir-ch** [comment]
I think the Go versions for Travis should be updated first.

**Comment by kortschak** [comment]
Yes. I've sent #42 to do that. Thanks

**Comment by kortschak** [comment]
PTAL

**Comment by sbinet** [comment]
# [Codecov](https://codecov.io/gh/gonum/exp/pull/41?src=pr&el=h1) Report
> Merging [#41](https://codecov.io/gh/gonum/exp/pull/41?src=pr&el=desc) into [master](https://codecov.io/gh/gonum/exp/commit/658383b751c008cc83a7e4cd4566e1f4061e361c&el=desc) will **not change** coverage by `%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/gonum/exp/pull/41?src=pr&el=tree)

```diff
@@           Coverage Diff           @@
##           master      #41   +/-   ##
=======================================
  Coverage   76.38%   76.38%           
=======================================
  Files          19       19           
  Lines        1575     1575           
=======================================
  Hits         1203     1203           
  Misses        244      244           
  Partials      128      128           
```



------

[Continue to review full report at Codecov](https://codecov.io/gh/gonum/exp/pull/41?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/gonum/exp/pull/41?src=pr&el=footer). Last update [658383b...628941e](https://codecov.io/gh/gonum/exp/pull/41?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Pull request merged**
