### PR TITLE
travis: update go versions

### PR DESCRIPTION
**Pull request by dvrkps**

### CODE REVIEW

**Comment by btracey** [comment]
We only test the last three versions, so when you add 1.9, delete 1.6 please. Thanks!

**Comment by btracey** [comment]
Also, could you please make a PR signing Authors and Contributors

**Comment by dvrkps** [comment]
"Also, could you please make a PR signing Authors and Contributors"
@btracey how to do that ?

**Comment by btracey** [comment]
It's in the gonum/gonum repository. There you will see an AUTHORS.md and a CONTRIBUTORS.md . You need to add your name so we can keep track of who has contributed.

**Pull request merged**
