### PR TITLE
Add linsolve package with iterative methods for solving linear systems

### PR DESCRIPTION
**Pull request by vladimir-ch**
The proposal with a short discussion can be found at https://groups.google.com/forum/#!topic/gonum-dev/nrPRhPR0c_s

I made effort to organize the commits into a natural sequence of steps to go from zero to the current state. 

@gonum/developers PTAL

### CODE REVIEW

**Comment by btracey** [comment]
I love having this here to see the full vision of the package. I think practically, it would be easiest for me to leave this open, and then have the list of commits here be a set of PRs that I could comment on.

I'm looking now at the high-level structure, but I'm noting a lot of small fixes I want (mostly documentation). It would be easier to address these one by one than trying to do it all here I think.

**Comment by vladimir-ch** [comment]
Sure, I can do a PR per commit. I'll start later today.

**Comment by btracey** [comment]
Just do the first one for now. It'll take a bit anyway to see the bigger picture.

**Comment by btracey** [comment]
Okay, I had a chance to look through this. It looks like quite a clean design. The biconjugate gradient implementation looks very clean. 

The main thing I want to check is if the iterative procedure is really necessary. In `optimize`, there's a lot of shared code. Maintaining stats, checking for convergence, etc. I realize the same pieces are here, but in optimize they overlap significantly. It's common to want to stop after a certain number of function evaluations, and so it's important to have a consistent way to count function evaluations. Without that entanglement, it's not hard to wrap a lot of the desired behavior behind interfaces.

It's not clear to me that these concepts are strongly coupled here. The only thing that gets checked for convergence is if the tolerance is sufficiently low, and then a check on the number of iterations that returns an error (so it doesn't seem like an expected path). I'm not sure if this is just because the package is in an early initial state, but want to check that you believe this is the right path, as opposed to each of the types implementing

```
type Iterative interface(sys System, x []float64, settings Settings
```
where the type implementing System can keep track of the calls to itself.

**Comment by vladimir-ch** [comment]
I think that using the reverse communication for Method is useful, even though perhaps for different reasons than in optimize. Linear solvers are often used at the inner-most level of other solvers, like solvers for nonlinear systems, in optimization in inexact Newton methods, in quadratic programming problems from FETI-based domain decomposition methods. It is useful if the outer iteration can have direct access or participate in the linear iteration because of for example custom stopping criteria. Even if the linear solver is used directly, it should be possible to use problem-specific stopping criterion. If the Method interface provides only something like a Solve method, then this would have to be given to Method somehow.

I still think that the current approach of directly using Method for full customization, and the convenient but slightly restricted Iterate function is good. Moreover, implementing a custom loop around CG is easy, and I would be the first to use it.

> The only thing that gets checked for convergence is if the tolerance is sufficiently low

This is the standard case but the convergence test should be ideally problem-specific.

> check on the number of iterations that returns an error (so it doesn't seem like an expected path)

It exists as a fail-safe mechanism to make sure we don't have an endless loop, it's not a serious stopping criterion. I will later add an exported error so that it can be checked by the caller. I don't think that in optimize terminating after a set number of function evaluations is an expected path because then nothing is known about the returned "solution".

> I'm not sure if this is just because the package is in an early initial state, but want to check that you 
> believe this is the right path, as opposed to each of the types implementing
>  type Iterative interface(sys System, x []float64, settings Settings
> where the type implementing System can keep track of the calls to itself.

I don't think that it belongs System to track the number of calls to itself. It would then have to have a logic to reset the number of calls. Similarly the preconditioner would have to track the calls to itself.

I thought about each type implementing its own loop without trying to bring them all under the same interface but as I write above I believe there is a benefit in having this two-level API: the low level with the possibility to participate in the iterative loop, and the higher level represented by the convenience function Iterative.

**Comment by vladimir-ch** [comment]
I'm closing this PR because it was kept open as a reference for a general idea/direction for `linsolve` but everything here has already been merged into master in the meantime.

**Pull request closed without merging**
